export enum ErrorCodesEnum {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  DEEZER_PLAYLIST_NOT_FOUND = "DEEZER_PLAYLIST_NOT_FOUND",
  DEEZER_PLAYLIST_PARSING_ERROR = "DEEZER_PLAYLIST_PARSING_ERROR",
  DEEZER_PLAYLIST_URL_INVALID = "DEEZER_PLAYLIST_URL_INVALID",
  DEEZER_PLAYLIST_NAME_MISSING = "DEEZER_PLAYLIST_NAME_MISSING",
  SPOTIFY_ACCESS_TOKEN_MISSING = "SPOTIFY_ACCESS_TOKEN_MISSING",
  SPOTIFY_PLAYLIST_CREATION_ERROR = "SPOTIFY_PLAYLIST_CREATION_ERROR",
}
